pipeline {

    agent any

    tools {
        maven 'Maven'
        jdk 'JDK8'
    }

    stages {

        stage('Checkout') {
            steps {
             git branch: 'master',url: 'https://github.com/Divyanshu-Developer-2004/Jenkins-Test-Repo-for-DevOps'
            }
        }

        stage('Build') {
            steps {
                dir('IEM_Jenkins_Project') {
                    bat 'mvn clean compile'
                }
            }
         
         
        }

        stage('Run JUnit Tests') {
            steps {
                dir('IEM_Jenkins_Project') {
                    bat 'mvn test'
                }
            }
        }

       stage('SonarQube Analysis') {
          steps {
          withSonarQubeEnv('SonarServer') {
            bat 'mvn clean verify sonar:sonar'
        }
    }
}

    }
}